services:
  fastapi:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/churn-prediction:amany217
    container_name: fastapi
    ports:
      - "80:8000"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9092:9092
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3002"
    depends_on:
      - prometheus        